deployment:
  tasks:
    - export REPOPATH=/home/tiseby/zbuduem.by/repository/bot-backend/*
    - export SITEPATH=/home/tiseby/zbuduem.by/bot-backend/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH